/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusIndexRouteImport } from './routes/status/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ProjectsProjectSlugIndexRouteImport } from './routes/projects/$projectSlug/index'
import { Route as JournalOperationalHabitsThatStickIndexRouteImport } from './routes/journal/operational-habits-that-stick/index'
import { Route as JournalModelFirstEngineeringIndexRouteImport } from './routes/journal/model-first-engineering/index'
import { Route as JournalAiCollaborationChecklistIndexRouteImport } from './routes/journal/ai-collaboration-checklist/index'
import { Route as AdminSyncIndexRouteImport } from './routes/admin/sync/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminOverviewIndexRouteImport } from './routes/admin/overview/index'
import { Route as AdminLogsIndexRouteImport } from './routes/admin/logs/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIndexRoute = StatusIndexRouteImport.update({
  id: '/status/',
  path: '/status/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSlugIndexRoute =
  ProjectsProjectSlugIndexRouteImport.update({
    id: '/projects/$projectSlug/',
    path: '/projects/$projectSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalOperationalHabitsThatStickIndexRoute =
  JournalOperationalHabitsThatStickIndexRouteImport.update({
    id: '/journal/operational-habits-that-stick/',
    path: '/journal/operational-habits-that-stick/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalModelFirstEngineeringIndexRoute =
  JournalModelFirstEngineeringIndexRouteImport.update({
    id: '/journal/model-first-engineering/',
    path: '/journal/model-first-engineering/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalAiCollaborationChecklistIndexRoute =
  JournalAiCollaborationChecklistIndexRouteImport.update({
    id: '/journal/ai-collaboration-checklist/',
    path: '/journal/ai-collaboration-checklist/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSyncIndexRoute = AdminSyncIndexRouteImport.update({
  id: '/admin/sync/',
  path: '/admin/sync/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOverviewIndexRoute = AdminOverviewIndexRouteImport.update({
  id: '/admin/overview/',
  path: '/admin/overview/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsIndexRoute = AdminLogsIndexRouteImport.update({
  id: '/admin/logs/',
  path: '/admin/logs/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/status/': typeof StatusIndexRoute
  '/admin/logs/': typeof AdminLogsIndexRoute
  '/admin/overview/': typeof AdminOverviewIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/sync/': typeof AdminSyncIndexRoute
  '/journal/ai-collaboration-checklist/': typeof JournalAiCollaborationChecklistIndexRoute
  '/journal/model-first-engineering/': typeof JournalModelFirstEngineeringIndexRoute
  '/journal/operational-habits-that-stick/': typeof JournalOperationalHabitsThatStickIndexRoute
  '/projects/$projectSlug/': typeof ProjectsProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/contact': typeof ContactIndexRoute
  '/journal': typeof JournalIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/status': typeof StatusIndexRoute
  '/admin/logs': typeof AdminLogsIndexRoute
  '/admin/overview': typeof AdminOverviewIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/sync': typeof AdminSyncIndexRoute
  '/journal/ai-collaboration-checklist': typeof JournalAiCollaborationChecklistIndexRoute
  '/journal/model-first-engineering': typeof JournalModelFirstEngineeringIndexRoute
  '/journal/operational-habits-that-stick': typeof JournalOperationalHabitsThatStickIndexRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/status/': typeof StatusIndexRoute
  '/admin/logs/': typeof AdminLogsIndexRoute
  '/admin/overview/': typeof AdminOverviewIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/sync/': typeof AdminSyncIndexRoute
  '/journal/ai-collaboration-checklist/': typeof JournalAiCollaborationChecklistIndexRoute
  '/journal/model-first-engineering/': typeof JournalModelFirstEngineeringIndexRoute
  '/journal/operational-habits-that-stick/': typeof JournalOperationalHabitsThatStickIndexRoute
  '/projects/$projectSlug/': typeof ProjectsProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/'
    | '/admin/'
    | '/contact/'
    | '/journal/'
    | '/projects/'
    | '/status/'
    | '/admin/logs/'
    | '/admin/overview/'
    | '/admin/projects/'
    | '/admin/sync/'
    | '/journal/ai-collaboration-checklist/'
    | '/journal/model-first-engineering/'
    | '/journal/operational-habits-that-stick/'
    | '/projects/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/journal'
    | '/projects'
    | '/status'
    | '/admin/logs'
    | '/admin/overview'
    | '/admin/projects'
    | '/admin/sync'
    | '/journal/ai-collaboration-checklist'
    | '/journal/model-first-engineering'
    | '/journal/operational-habits-that-stick'
    | '/projects/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/about/'
    | '/admin/'
    | '/contact/'
    | '/journal/'
    | '/projects/'
    | '/status/'
    | '/admin/logs/'
    | '/admin/overview/'
    | '/admin/projects/'
    | '/admin/sync/'
    | '/journal/ai-collaboration-checklist/'
    | '/journal/model-first-engineering/'
    | '/journal/operational-habits-that-stick/'
    | '/projects/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  StatusIndexRoute: typeof StatusIndexRoute
  AdminLogsIndexRoute: typeof AdminLogsIndexRoute
  AdminOverviewIndexRoute: typeof AdminOverviewIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminSyncIndexRoute: typeof AdminSyncIndexRoute
  JournalAiCollaborationChecklistIndexRoute: typeof JournalAiCollaborationChecklistIndexRoute
  JournalModelFirstEngineeringIndexRoute: typeof JournalModelFirstEngineeringIndexRoute
  JournalOperationalHabitsThatStickIndexRoute: typeof JournalOperationalHabitsThatStickIndexRoute
  ProjectsProjectSlugIndexRoute: typeof ProjectsProjectSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/': {
      id: '/status/'
      path: '/status'
      fullPath: '/status/'
      preLoaderRoute: typeof StatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug/': {
      id: '/projects/$projectSlug/'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug/'
      preLoaderRoute: typeof ProjectsProjectSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/operational-habits-that-stick/': {
      id: '/journal/operational-habits-that-stick/'
      path: '/journal/operational-habits-that-stick'
      fullPath: '/journal/operational-habits-that-stick/'
      preLoaderRoute: typeof JournalOperationalHabitsThatStickIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/model-first-engineering/': {
      id: '/journal/model-first-engineering/'
      path: '/journal/model-first-engineering'
      fullPath: '/journal/model-first-engineering/'
      preLoaderRoute: typeof JournalModelFirstEngineeringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/ai-collaboration-checklist/': {
      id: '/journal/ai-collaboration-checklist/'
      path: '/journal/ai-collaboration-checklist'
      fullPath: '/journal/ai-collaboration-checklist/'
      preLoaderRoute: typeof JournalAiCollaborationChecklistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sync/': {
      id: '/admin/sync/'
      path: '/admin/sync'
      fullPath: '/admin/sync/'
      preLoaderRoute: typeof AdminSyncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/overview/': {
      id: '/admin/overview/'
      path: '/admin/overview'
      fullPath: '/admin/overview/'
      preLoaderRoute: typeof AdminOverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs/': {
      id: '/admin/logs/'
      path: '/admin/logs'
      fullPath: '/admin/logs/'
      preLoaderRoute: typeof AdminLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  StatusIndexRoute: StatusIndexRoute,
  AdminLogsIndexRoute: AdminLogsIndexRoute,
  AdminOverviewIndexRoute: AdminOverviewIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminSyncIndexRoute: AdminSyncIndexRoute,
  JournalAiCollaborationChecklistIndexRoute:
    JournalAiCollaborationChecklistIndexRoute,
  JournalModelFirstEngineeringIndexRoute:
    JournalModelFirstEngineeringIndexRoute,
  JournalOperationalHabitsThatStickIndexRoute:
    JournalOperationalHabitsThatStickIndexRoute,
  ProjectsProjectSlugIndexRoute: ProjectsProjectSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
