/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexDothtmlRouteImport } from './routes/index[.]html'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusIndexRouteImport } from './routes/status/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as StatusIndexDothtmlRouteImport } from './routes/status/index[.]html'
import { Route as ProjectsIndexDothtmlRouteImport } from './routes/projects/index[.]html'
import { Route as JournalIndexDothtmlRouteImport } from './routes/journal/index[.]html'
import { Route as ContactIndexDothtmlRouteImport } from './routes/contact/index[.]html'
import { Route as AdminIndexDothtmlRouteImport } from './routes/admin/index[.]html'
import { Route as AboutIndexDothtmlRouteImport } from './routes/about/index[.]html'
import { Route as ProjectsProjectSlugIndexRouteImport } from './routes/projects/$projectSlug/index'
import { Route as JournalOperationalHabitsThatStickIndexRouteImport } from './routes/journal/operational-habits-that-stick/index'
import { Route as JournalModelFirstEngineeringIndexRouteImport } from './routes/journal/model-first-engineering/index'
import { Route as JournalAiCollaborationChecklistIndexRouteImport } from './routes/journal/ai-collaboration-checklist/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as ProjectsProjectSlugIndexDothtmlRouteImport } from './routes/projects/$projectSlug/index[.]html'
import { Route as JournalOperationalHabitsThatStickIndexDothtmlRouteImport } from './routes/journal/operational-habits-that-stick/index[.]html'
import { Route as JournalModelFirstEngineeringIndexDothtmlRouteImport } from './routes/journal/model-first-engineering/index[.]html'
import { Route as JournalAiCollaborationChecklistIndexDothtmlRouteImport } from './routes/journal/ai-collaboration-checklist/index[.]html'
import { Route as AdminProjectsIndexDothtmlRouteImport } from './routes/admin/projects/index[.]html'

const IndexDothtmlRoute = IndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIndexRoute = StatusIndexRouteImport.update({
  id: '/status/',
  path: '/status/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIndexDothtmlRoute = StatusIndexDothtmlRouteImport.update({
  id: '/status/index.html',
  path: '/status/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexDothtmlRoute = ProjectsIndexDothtmlRouteImport.update({
  id: '/projects/index.html',
  path: '/projects/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexDothtmlRoute = JournalIndexDothtmlRouteImport.update({
  id: '/journal/index.html',
  path: '/journal/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexDothtmlRoute = ContactIndexDothtmlRouteImport.update({
  id: '/contact/index.html',
  path: '/contact/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexDothtmlRoute = AdminIndexDothtmlRouteImport.update({
  id: '/admin/index.html',
  path: '/admin/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexDothtmlRoute = AboutIndexDothtmlRouteImport.update({
  id: '/about/index.html',
  path: '/about/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSlugIndexRoute =
  ProjectsProjectSlugIndexRouteImport.update({
    id: '/projects/$projectSlug/',
    path: '/projects/$projectSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalOperationalHabitsThatStickIndexRoute =
  JournalOperationalHabitsThatStickIndexRouteImport.update({
    id: '/journal/operational-habits-that-stick/',
    path: '/journal/operational-habits-that-stick/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalModelFirstEngineeringIndexRoute =
  JournalModelFirstEngineeringIndexRouteImport.update({
    id: '/journal/model-first-engineering/',
    path: '/journal/model-first-engineering/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalAiCollaborationChecklistIndexRoute =
  JournalAiCollaborationChecklistIndexRouteImport.update({
    id: '/journal/ai-collaboration-checklist/',
    path: '/journal/ai-collaboration-checklist/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSlugIndexDothtmlRoute =
  ProjectsProjectSlugIndexDothtmlRouteImport.update({
    id: '/projects/$projectSlug/index.html',
    path: '/projects/$projectSlug/index.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalOperationalHabitsThatStickIndexDothtmlRoute =
  JournalOperationalHabitsThatStickIndexDothtmlRouteImport.update({
    id: '/journal/operational-habits-that-stick/index.html',
    path: '/journal/operational-habits-that-stick/index.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalModelFirstEngineeringIndexDothtmlRoute =
  JournalModelFirstEngineeringIndexDothtmlRouteImport.update({
    id: '/journal/model-first-engineering/index.html',
    path: '/journal/model-first-engineering/index.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalAiCollaborationChecklistIndexDothtmlRoute =
  JournalAiCollaborationChecklistIndexDothtmlRouteImport.update({
    id: '/journal/ai-collaboration-checklist/index.html',
    path: '/journal/ai-collaboration-checklist/index.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProjectsIndexDothtmlRoute =
  AdminProjectsIndexDothtmlRouteImport.update({
    id: '/admin/projects/index.html',
    path: '/admin/projects/index.html',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/index.html': typeof IndexDothtmlRoute
  '/about/index.html': typeof AboutIndexDothtmlRoute
  '/admin/index.html': typeof AdminIndexDothtmlRoute
  '/contact/index.html': typeof ContactIndexDothtmlRoute
  '/journal/index.html': typeof JournalIndexDothtmlRoute
  '/projects/index.html': typeof ProjectsIndexDothtmlRoute
  '/status/index.html': typeof StatusIndexDothtmlRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/status/': typeof StatusIndexRoute
  '/admin/projects/index.html': typeof AdminProjectsIndexDothtmlRoute
  '/journal/ai-collaboration-checklist/index.html': typeof JournalAiCollaborationChecklistIndexDothtmlRoute
  '/journal/model-first-engineering/index.html': typeof JournalModelFirstEngineeringIndexDothtmlRoute
  '/journal/operational-habits-that-stick/index.html': typeof JournalOperationalHabitsThatStickIndexDothtmlRoute
  '/projects/$projectSlug/index.html': typeof ProjectsProjectSlugIndexDothtmlRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/journal/ai-collaboration-checklist/': typeof JournalAiCollaborationChecklistIndexRoute
  '/journal/model-first-engineering/': typeof JournalModelFirstEngineeringIndexRoute
  '/journal/operational-habits-that-stick/': typeof JournalOperationalHabitsThatStickIndexRoute
  '/projects/$projectSlug/': typeof ProjectsProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/index.html': typeof IndexDothtmlRoute
  '/about/index.html': typeof AboutIndexDothtmlRoute
  '/admin/index.html': typeof AdminIndexDothtmlRoute
  '/contact/index.html': typeof ContactIndexDothtmlRoute
  '/journal/index.html': typeof JournalIndexDothtmlRoute
  '/projects/index.html': typeof ProjectsIndexDothtmlRoute
  '/status/index.html': typeof StatusIndexDothtmlRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/contact': typeof ContactIndexRoute
  '/journal': typeof JournalIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/status': typeof StatusIndexRoute
  '/admin/projects/index.html': typeof AdminProjectsIndexDothtmlRoute
  '/journal/ai-collaboration-checklist/index.html': typeof JournalAiCollaborationChecklistIndexDothtmlRoute
  '/journal/model-first-engineering/index.html': typeof JournalModelFirstEngineeringIndexDothtmlRoute
  '/journal/operational-habits-that-stick/index.html': typeof JournalOperationalHabitsThatStickIndexDothtmlRoute
  '/projects/$projectSlug/index.html': typeof ProjectsProjectSlugIndexDothtmlRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/journal/ai-collaboration-checklist': typeof JournalAiCollaborationChecklistIndexRoute
  '/journal/model-first-engineering': typeof JournalModelFirstEngineeringIndexRoute
  '/journal/operational-habits-that-stick': typeof JournalOperationalHabitsThatStickIndexRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/index.html': typeof IndexDothtmlRoute
  '/about/index.html': typeof AboutIndexDothtmlRoute
  '/admin/index.html': typeof AdminIndexDothtmlRoute
  '/contact/index.html': typeof ContactIndexDothtmlRoute
  '/journal/index.html': typeof JournalIndexDothtmlRoute
  '/projects/index.html': typeof ProjectsIndexDothtmlRoute
  '/status/index.html': typeof StatusIndexDothtmlRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/status/': typeof StatusIndexRoute
  '/admin/projects/index.html': typeof AdminProjectsIndexDothtmlRoute
  '/journal/ai-collaboration-checklist/index.html': typeof JournalAiCollaborationChecklistIndexDothtmlRoute
  '/journal/model-first-engineering/index.html': typeof JournalModelFirstEngineeringIndexDothtmlRoute
  '/journal/operational-habits-that-stick/index.html': typeof JournalOperationalHabitsThatStickIndexDothtmlRoute
  '/projects/$projectSlug/index.html': typeof ProjectsProjectSlugIndexDothtmlRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/journal/ai-collaboration-checklist/': typeof JournalAiCollaborationChecklistIndexRoute
  '/journal/model-first-engineering/': typeof JournalModelFirstEngineeringIndexRoute
  '/journal/operational-habits-that-stick/': typeof JournalOperationalHabitsThatStickIndexRoute
  '/projects/$projectSlug/': typeof ProjectsProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/index.html'
    | '/about/index.html'
    | '/admin/index.html'
    | '/contact/index.html'
    | '/journal/index.html'
    | '/projects/index.html'
    | '/status/index.html'
    | '/about/'
    | '/admin/'
    | '/contact/'
    | '/journal/'
    | '/projects/'
    | '/status/'
    | '/admin/projects/index.html'
    | '/journal/ai-collaboration-checklist/index.html'
    | '/journal/model-first-engineering/index.html'
    | '/journal/operational-habits-that-stick/index.html'
    | '/projects/$projectSlug/index.html'
    | '/admin/projects/'
    | '/journal/ai-collaboration-checklist/'
    | '/journal/model-first-engineering/'
    | '/journal/operational-habits-that-stick/'
    | '/projects/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/index.html'
    | '/about/index.html'
    | '/admin/index.html'
    | '/contact/index.html'
    | '/journal/index.html'
    | '/projects/index.html'
    | '/status/index.html'
    | '/about'
    | '/admin'
    | '/contact'
    | '/journal'
    | '/projects'
    | '/status'
    | '/admin/projects/index.html'
    | '/journal/ai-collaboration-checklist/index.html'
    | '/journal/model-first-engineering/index.html'
    | '/journal/operational-habits-that-stick/index.html'
    | '/projects/$projectSlug/index.html'
    | '/admin/projects'
    | '/journal/ai-collaboration-checklist'
    | '/journal/model-first-engineering'
    | '/journal/operational-habits-that-stick'
    | '/projects/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/index.html'
    | '/about/index.html'
    | '/admin/index.html'
    | '/contact/index.html'
    | '/journal/index.html'
    | '/projects/index.html'
    | '/status/index.html'
    | '/about/'
    | '/admin/'
    | '/contact/'
    | '/journal/'
    | '/projects/'
    | '/status/'
    | '/admin/projects/index.html'
    | '/journal/ai-collaboration-checklist/index.html'
    | '/journal/model-first-engineering/index.html'
    | '/journal/operational-habits-that-stick/index.html'
    | '/projects/$projectSlug/index.html'
    | '/admin/projects/'
    | '/journal/ai-collaboration-checklist/'
    | '/journal/model-first-engineering/'
    | '/journal/operational-habits-that-stick/'
    | '/projects/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexDothtmlRoute: typeof IndexDothtmlRoute
  AboutIndexDothtmlRoute: typeof AboutIndexDothtmlRoute
  AdminIndexDothtmlRoute: typeof AdminIndexDothtmlRoute
  ContactIndexDothtmlRoute: typeof ContactIndexDothtmlRoute
  JournalIndexDothtmlRoute: typeof JournalIndexDothtmlRoute
  ProjectsIndexDothtmlRoute: typeof ProjectsIndexDothtmlRoute
  StatusIndexDothtmlRoute: typeof StatusIndexDothtmlRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  StatusIndexRoute: typeof StatusIndexRoute
  AdminProjectsIndexDothtmlRoute: typeof AdminProjectsIndexDothtmlRoute
  JournalAiCollaborationChecklistIndexDothtmlRoute: typeof JournalAiCollaborationChecklistIndexDothtmlRoute
  JournalModelFirstEngineeringIndexDothtmlRoute: typeof JournalModelFirstEngineeringIndexDothtmlRoute
  JournalOperationalHabitsThatStickIndexDothtmlRoute: typeof JournalOperationalHabitsThatStickIndexDothtmlRoute
  ProjectsProjectSlugIndexDothtmlRoute: typeof ProjectsProjectSlugIndexDothtmlRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  JournalAiCollaborationChecklistIndexRoute: typeof JournalAiCollaborationChecklistIndexRoute
  JournalModelFirstEngineeringIndexRoute: typeof JournalModelFirstEngineeringIndexRoute
  JournalOperationalHabitsThatStickIndexRoute: typeof JournalOperationalHabitsThatStickIndexRoute
  ProjectsProjectSlugIndexRoute: typeof ProjectsProjectSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index.html': {
      id: '/index.html'
      path: '/index.html'
      fullPath: '/index.html'
      preLoaderRoute: typeof IndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/': {
      id: '/status/'
      path: '/status'
      fullPath: '/status/'
      preLoaderRoute: typeof StatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/index.html': {
      id: '/status/index.html'
      path: '/status/index.html'
      fullPath: '/status/index.html'
      preLoaderRoute: typeof StatusIndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/index.html': {
      id: '/projects/index.html'
      path: '/projects/index.html'
      fullPath: '/projects/index.html'
      preLoaderRoute: typeof ProjectsIndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/index.html': {
      id: '/journal/index.html'
      path: '/journal/index.html'
      fullPath: '/journal/index.html'
      preLoaderRoute: typeof JournalIndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/index.html': {
      id: '/contact/index.html'
      path: '/contact/index.html'
      fullPath: '/contact/index.html'
      preLoaderRoute: typeof ContactIndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/index.html': {
      id: '/admin/index.html'
      path: '/admin/index.html'
      fullPath: '/admin/index.html'
      preLoaderRoute: typeof AdminIndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/index.html': {
      id: '/about/index.html'
      path: '/about/index.html'
      fullPath: '/about/index.html'
      preLoaderRoute: typeof AboutIndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug/': {
      id: '/projects/$projectSlug/'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug/'
      preLoaderRoute: typeof ProjectsProjectSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/operational-habits-that-stick/': {
      id: '/journal/operational-habits-that-stick/'
      path: '/journal/operational-habits-that-stick'
      fullPath: '/journal/operational-habits-that-stick/'
      preLoaderRoute: typeof JournalOperationalHabitsThatStickIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/model-first-engineering/': {
      id: '/journal/model-first-engineering/'
      path: '/journal/model-first-engineering'
      fullPath: '/journal/model-first-engineering/'
      preLoaderRoute: typeof JournalModelFirstEngineeringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/ai-collaboration-checklist/': {
      id: '/journal/ai-collaboration-checklist/'
      path: '/journal/ai-collaboration-checklist'
      fullPath: '/journal/ai-collaboration-checklist/'
      preLoaderRoute: typeof JournalAiCollaborationChecklistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug/index.html': {
      id: '/projects/$projectSlug/index.html'
      path: '/projects/$projectSlug/index.html'
      fullPath: '/projects/$projectSlug/index.html'
      preLoaderRoute: typeof ProjectsProjectSlugIndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/operational-habits-that-stick/index.html': {
      id: '/journal/operational-habits-that-stick/index.html'
      path: '/journal/operational-habits-that-stick/index.html'
      fullPath: '/journal/operational-habits-that-stick/index.html'
      preLoaderRoute: typeof JournalOperationalHabitsThatStickIndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/model-first-engineering/index.html': {
      id: '/journal/model-first-engineering/index.html'
      path: '/journal/model-first-engineering/index.html'
      fullPath: '/journal/model-first-engineering/index.html'
      preLoaderRoute: typeof JournalModelFirstEngineeringIndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/ai-collaboration-checklist/index.html': {
      id: '/journal/ai-collaboration-checklist/index.html'
      path: '/journal/ai-collaboration-checklist/index.html'
      fullPath: '/journal/ai-collaboration-checklist/index.html'
      preLoaderRoute: typeof JournalAiCollaborationChecklistIndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/index.html': {
      id: '/admin/projects/index.html'
      path: '/admin/projects/index.html'
      fullPath: '/admin/projects/index.html'
      preLoaderRoute: typeof AdminProjectsIndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexDothtmlRoute: IndexDothtmlRoute,
  AboutIndexDothtmlRoute: AboutIndexDothtmlRoute,
  AdminIndexDothtmlRoute: AdminIndexDothtmlRoute,
  ContactIndexDothtmlRoute: ContactIndexDothtmlRoute,
  JournalIndexDothtmlRoute: JournalIndexDothtmlRoute,
  ProjectsIndexDothtmlRoute: ProjectsIndexDothtmlRoute,
  StatusIndexDothtmlRoute: StatusIndexDothtmlRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  StatusIndexRoute: StatusIndexRoute,
  AdminProjectsIndexDothtmlRoute: AdminProjectsIndexDothtmlRoute,
  JournalAiCollaborationChecklistIndexDothtmlRoute:
    JournalAiCollaborationChecklistIndexDothtmlRoute,
  JournalModelFirstEngineeringIndexDothtmlRoute:
    JournalModelFirstEngineeringIndexDothtmlRoute,
  JournalOperationalHabitsThatStickIndexDothtmlRoute:
    JournalOperationalHabitsThatStickIndexDothtmlRoute,
  ProjectsProjectSlugIndexDothtmlRoute: ProjectsProjectSlugIndexDothtmlRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  JournalAiCollaborationChecklistIndexRoute:
    JournalAiCollaborationChecklistIndexRoute,
  JournalModelFirstEngineeringIndexRoute:
    JournalModelFirstEngineeringIndexRoute,
  JournalOperationalHabitsThatStickIndexRoute:
    JournalOperationalHabitsThatStickIndexRoute,
  ProjectsProjectSlugIndexRoute: ProjectsProjectSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
